package com.knowledge.springboot.dto;

import java.util.List;

/**
 * 知识树数据响应DTO
 */
public class KnowledgeTreeDataResponse {

    private Long treeId;
    private String name;
    private String lastUpdateTime;
    private Integer totalNodes;
    private Integer associatedNotesCount;
    private TreeNode tree;

    // 内部类：树节点
    public static class TreeNode {
        private String nodeId;
        private String name;
        private Integer level;
        private Integer progress;
        private String description;
        private List<String> keywords;
        private Integer associatedNotesCount;
        private Boolean isAutoGenerated;
        private List<String> sourceNoteIds;
        private List<AssociatedNoteInfo> associatedNotes;
        private List<TreeNode> children;

        private String status;

        // Getters and Setters
        public String getNodeId() {
            return nodeId;
        }

        public void setNodeId(String nodeId) {
            this.nodeId = nodeId;
        }

        public String getName() {
            return name;
        }

        public void setName(String name) {
            this.name = name;
        }

        public Integer getLevel() {
            return level;
        }

        public void setLevel(Integer level) {
            this.level = level;
        }

        public Integer getProgress() {
            return progress;
        }

        public void setProgress(Integer progress) {
            this.progress = progress;
        }

        public String getDescription() {
            return description;
        }

        public void setDescription(String description) {
            this.description = description;
        }

        public List<String> getKeywords() {
            return keywords;
        }

        public void setKeywords(List<String> keywords) {
            this.keywords = keywords;
        }

        public Integer getAssociatedNotesCount() {
            return associatedNotesCount;
        }

        public void setAssociatedNotesCount(Integer associatedNotesCount) {
            this.associatedNotesCount = associatedNotesCount;
        }

        public Boolean getIsAutoGenerated() {
            return isAutoGenerated;
        }

        public void setIsAutoGenerated(Boolean isAutoGenerated) {
            this.isAutoGenerated = isAutoGenerated;
        }

        public List<String> getSourceNoteIds() {
            return sourceNoteIds;
        }

        public void setSourceNoteIds(List<String> sourceNoteIds) {
            this.sourceNoteIds = sourceNoteIds;
        }

        public List<AssociatedNoteInfo> getAssociatedNotes() {
            return associatedNotes;
        }

        public void setAssociatedNotes(List<AssociatedNoteInfo> associatedNotes) {
            this.associatedNotes = associatedNotes;
        }

        public List<TreeNode> getChildren() {
            return children;
        }

        public void setChildren(List<TreeNode> children) {
            this.children = children;
        }


        public String getStatus() {
            return status;
        }


        public void setStatus(String status) {
            this.status = status;
        }
    }

    // 内部类：关联笔记信息
    public static class AssociatedNoteInfo {
        private String noteId;
        private String title;
        private Double relevanceScore;
        private List<String> associatedKnowledgePoints;

        // Getters and Setters
        public String getNoteId() {
            return noteId;
        }

        public void setNoteId(String noteId) {
            this.noteId = noteId;
        }

        public String getTitle() {
            return title;
        }

        public void setTitle(String title) {
            this.title = title;
        }

        public Double getRelevanceScore() {
            return relevanceScore;
        }

        public void setRelevanceScore(Double relevanceScore) {
            this.relevanceScore = relevanceScore;
        }

        public List<String> getAssociatedKnowledgePoints() {
            return associatedKnowledgePoints;
        }

        public void setAssociatedKnowledgePoints(List<String> associatedKnowledgePoints) {
            this.associatedKnowledgePoints = associatedKnowledgePoints;
        }
    }

    // Getters and Setters
    public Long getTreeId() {
        return treeId;
    }

    public void setTreeId(Long treeId) {
        this.treeId = treeId;
    }

    public String getName() {
        return name;
    }

    public void setName(String name) {
        this.name = name;
    }

    public String getLastUpdateTime() {
        return lastUpdateTime;
    }

    public void setLastUpdateTime(String lastUpdateTime) {
        this.lastUpdateTime = lastUpdateTime;
    }

    public Integer getTotalNodes() {
        return totalNodes;
    }

    public void setTotalNodes(Integer totalNodes) {
        this.totalNodes = totalNodes;
    }

    public Integer getAssociatedNotesCount() {
        return associatedNotesCount;
    }

    public void setAssociatedNotesCount(Integer associatedNotesCount) {
        this.associatedNotesCount = associatedNotesCount;
    }

    public TreeNode getTree() {
        return tree;
    }

    public void setTree(TreeNode tree) {
        this.tree = tree;
    }
}
