package com.knowledge.springboot.domain;

import org.springframework.data.annotation.Id;
import org.springframework.data.mongodb.core.mapping.Document;
import org.springframework.data.mongodb.core.mapping.Field;

import java.util.Date;
import java.util.List;

/**
 * 知识节点实体类
 */
@Document(collection = "knowledge_nodes")
public class KnowledgeNode {

    @Id
    private String id;

    @Field("nodeId")
    private String nodeId;

    @Field("treeId")
    private Long treeId;

    @Field("userId")
    private String userId;

    @Field("name")
    private String name;

    @Field("category")
    private String category;

    @Field("description")
    private String description;

    @Field("parentNodeId")
    private String parentNodeId;

    @Field("childrenNodeIds")
    private List<String> childrenNodeIds;

    @Field("level")
    private Integer level;

    @Field("path")
    private List<String> path;

    @Field("position")
    private Position position;

    @Field("progress")
    private Integer progress;

    @Field("keywords")
    private List<String> keywords;

    @Field("relatedNodeIds")
    private List<String> relatedNodeIds;

    @Field("associatedNotes")
    private List<AssociatedNote> associatedNotes;

    @Field("metadata")
    private NodeMetadata metadata;

    @Field("isAutoGenerated")
    private Boolean isAutoGenerated;

    @Field("sourceNoteIds")
    private List<String> sourceNoteIds;

    @Field("createdAt")
    private Date createdAt;

    @Field("updatedAt")
    private Date updatedAt;

    // 内部类：位置信息
    public static class Position {
        private Double x;
        private Double y;
        private Integer order;

        public Position() {}

        public Position(Double x, Double y, Integer order) {
            this.x = x;
            this.y = y;
            this.order = order;
        }

        // Getters and Setters
        public Double getX() {
            return x;
        }

        public void setX(Double x) {
            this.x = x;
        }

        public Double getY() {
            return y;
        }

        public void setY(Double y) {
            this.y = y;
        }

        public Integer getOrder() {
            return order;
        }

        public void setOrder(Integer order) {
            this.order = order;
        }
    }

    // 内部类：关联笔记信息
    public static class AssociatedNote {
        private String noteId;
        private String title;
        private List<String> associatedKnowledgePoints;
        private Date associationTime;
        private Double relevanceScore;

        public AssociatedNote() {}

        public AssociatedNote(String noteId, String title, List<String> associatedKnowledgePoints,
                            Date associationTime, Double relevanceScore) {
            this.noteId = noteId;
            this.title = title;
            this.associatedKnowledgePoints = associatedKnowledgePoints;
            this.associationTime = associationTime;
            this.relevanceScore = relevanceScore;
        }

        // Getters and Setters
        public String getNoteId() {
            return noteId;
        }

        public void setNoteId(String noteId) {
            this.noteId = noteId;
        }

        public String getTitle() {
            return title;
        }

        public void setTitle(String title) {
            this.title = title;
        }

        public List<String> getAssociatedKnowledgePoints() {
            return associatedKnowledgePoints;
        }

        public void setAssociatedKnowledgePoints(List<String> associatedKnowledgePoints) {
            this.associatedKnowledgePoints = associatedKnowledgePoints;
        }

        public Date getAssociationTime() {
            return associationTime;
        }

        public void setAssociationTime(Date associationTime) {
            this.associationTime = associationTime;
        }

        public Double getRelevanceScore() {
            return relevanceScore;
        }

        public void setRelevanceScore(Double relevanceScore) {
            this.relevanceScore = relevanceScore;
        }
    }

    // 内部类：节点元数据
    public static class NodeMetadata {
        private String difficulty;
        private String importance;
        private Integer estimatedLearningTime;
        private List<String> prerequisites;

        public NodeMetadata() {}

        public NodeMetadata(String difficulty, String importance, Integer estimatedLearningTime, List<String> prerequisites) {
            this.difficulty = difficulty;
            this.importance = importance;
            this.estimatedLearningTime = estimatedLearningTime;
            this.prerequisites = prerequisites;
        }

        // Getters and Setters
        public String getDifficulty() {
            return difficulty;
        }

        public void setDifficulty(String difficulty) {
            this.difficulty = difficulty;
        }

        public String getImportance() {
            return importance;
        }

        public void setImportance(String importance) {
            this.importance = importance;
        }

        public Integer getEstimatedLearningTime() {
            return estimatedLearningTime;
        }

        public void setEstimatedLearningTime(Integer estimatedLearningTime) {
            this.estimatedLearningTime = estimatedLearningTime;
        }

        public List<String> getPrerequisites() {
            return prerequisites;
        }

        public void setPrerequisites(List<String> prerequisites) {
            this.prerequisites = prerequisites;
        }
    }

    // 构造函数
    public KnowledgeNode() {
        this.createdAt = new Date();
        this.updatedAt = new Date();
        this.progress = 0;
        this.isAutoGenerated = false;
    }

    // Getters and Setters
    public String getId() {
        return id;
    }

    public void setId(String id) {
        this.id = id;
    }

    public String getNodeId() {
        return nodeId;
    }

    public void setNodeId(String nodeId) {
        this.nodeId = nodeId;
    }

    public Long getTreeId() {
        return treeId;
    }

    public void setTreeId(Long treeId) {
        this.treeId = treeId;
    }

    public String getUserId() {
        return userId;
    }

    public void setUserId(String userId) {
        this.userId = userId;
    }

    public String getName() {
        return name;
    }

    public void setName(String name) {
        this.name = name;
    }

    public String getCategory() {
        return category;
    }

    public void setCategory(String category) {
        this.category = category;
    }

    public String getDescription() {
        return description;
    }

    public void setDescription(String description) {
        this.description = description;
    }

    public String getParentNodeId() {
        return parentNodeId;
    }

    public void setParentNodeId(String parentNodeId) {
        this.parentNodeId = parentNodeId;
    }

    public List<String> getChildrenNodeIds() {
        return childrenNodeIds;
    }

    public void setChildrenNodeIds(List<String> childrenNodeIds) {
        this.childrenNodeIds = childrenNodeIds;
    }

    public Integer getLevel() {
        return level;
    }

    public void setLevel(Integer level) {
        this.level = level;
    }

    public List<String> getPath() {
        return path;
    }

    public void setPath(List<String> path) {
        this.path = path;
    }

    public Position getPosition() {
        return position;
    }

    public void setPosition(Position position) {
        this.position = position;
    }

    public Integer getProgress() {
        return progress;
    }

    public void setProgress(Integer progress) {
        this.progress = progress;
    }

    public List<String> getKeywords() {
        return keywords;
    }

    public void setKeywords(List<String> keywords) {
        this.keywords = keywords;
    }

    public List<String> getRelatedNodeIds() {
        return relatedNodeIds;
    }

    public void setRelatedNodeIds(List<String> relatedNodeIds) {
        this.relatedNodeIds = relatedNodeIds;
    }

    public List<AssociatedNote> getAssociatedNotes() {
        return associatedNotes;
    }

    public void setAssociatedNotes(List<AssociatedNote> associatedNotes) {
        this.associatedNotes = associatedNotes;
    }

    public NodeMetadata getMetadata() {
        return metadata;
    }

    public void setMetadata(NodeMetadata metadata) {
        this.metadata = metadata;
    }

    public Boolean getIsAutoGenerated() {
        return isAutoGenerated;
    }

    public void setIsAutoGenerated(Boolean isAutoGenerated) {
        this.isAutoGenerated = isAutoGenerated;
    }

    public List<String> getSourceNoteIds() {
        return sourceNoteIds;
    }

    public void setSourceNoteIds(List<String> sourceNoteIds) {
        this.sourceNoteIds = sourceNoteIds;
    }

    public Date getCreatedAt() {
        return createdAt;
    }

    public void setCreatedAt(Date createdAt) {
        this.createdAt = createdAt;
    }

    public Date getUpdatedAt() {
        return updatedAt;
    }

    public void setUpdatedAt(Date updatedAt) {
        this.updatedAt = updatedAt;
    }
}
